### ISSUE TITLE
How to call setupAll

### ISSUE THREAD

**Issue by Phaisarnrungpana** [olexale/bdd_widget_test#14]
Hey @olexale 

This is very cool plugins and very easy to use.

If you have a time. Can you provide example how to call setupAll method with your plugins.

**Comment by olexale** [comment]
Hey! Thanks!

`setupAll` method was omitted intentionally. Here is a quote from [the documentation](https://api.flutter.dev/flutter/flutter_test/setUpAll.html).

> Note: This function makes it very easy to accidentally introduce hidden dependencies between tests that should be isolated. In general, you should prefer setUp, and only use setUpAll if the callback is prohibitively slow.

The other problem with `setUp` and `setupAll` methods is that it is not possible to use `WidgetTester tester` inside them. So the plugin generates its own `setUp` method (which is called `bddSetUp`) when a `Background` section is provided. You may find an example [here](https://github.com/olexale/flutteristas_conf_2021/blob/main/space_launches/test/feature/space_launch.feature) and here is a [video tutorial](https://youtu.be/YB4Efi7utc0) for this repository.

Is there a reason why you want to have a `setupAll` method?

**Comment by fredgrott** [comment]
Let's if I can guess. It might be to set up mocks, for example mocking a view model dependency. But if your bddSetUp is public then obviously we could use that I assume.

Nice plugin btw, beats having to setup Gherkin manually!

**Comment by olexale** [comment]
@fredgrott, you may set up mocks using regular steps like in [this sample](https://github.com/olexale/finished-flutter-firebase-ddd-course/blob/master/test/feature/sign_in.feature) and if you need to share steps between scenarios - use `Background` section as it's shown [here](https://github.com/olexale/flutteristas_conf_2021/blob/main/space_launches/test/feature/space_launch.feature).

Thanks, I'm glad you find it useful!

**Comment by olexale** [comment]
@Phaisarnrungpana, is this ticket is still actual? Should we close it?

**Comment by Phaisarnrungpana** [comment]
@olexale Yes., like @fredgrott said. I use bloc pattern and use mocktail to mock some dependencies. I will try to implement your example first. If I have a problem or any question I will ask you again. Thank you very much.
