### ISSUE TITLE
Support integration_test

### ISSUE THREAD

**Issue by WahdanZ** [olexale/bdd_widget_test#16]
can this package support integration_test as well widget test, because I think the same code can use for the integration test just need to add the following line?  ad the beginning of the main method 
```dart
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
```
and also the output folder to integration_test

**Comment by olexale** [comment]
Integration tests are not supported as of now but I plan to add them in a week or two.

**Comment by neiljaywarner** [comment]
@olexale  any update?  This would be super helpful and exciting.  Thanks!

**Comment by neiljaywarner** [comment]
@olexale  proposal: please put the generated code in a testShared directory so it is easy to use in widget tests and integration tests.

your library seems fantastic so far.
thanks

**Comment by olexale** [comment]
Hi folks,

Integration tests support was added in `1.1.0`. Here is [short documentation](https://github.com/olexale/bdd_widget_test#how-to-write-integration-tests) with a description of how to enable them in your projects.

[example](https://github.com/olexale/bdd_widget_test/tree/master/example) app was updated with integration support as well, so if something goes wrong - feel free to check it first.

Looking forward to feedback from you!

Best,
Oleksandr

**Comment by olexale** [comment]
Hi folks. 

Okay, seems like everything is working fine (at least on my project 😅) so I assume that it works for you as well. Closing this issue. Feel free to re-open it in case of any questions or comments.

Cheers,
Oleksandr
