### ISSUE TITLE
Error when custom step folder in integration tests

### ISSUE THREAD

**Issue by jamontes79** [olexale/bdd_widget_test#23]
First of all thanks for this great library.

I have an error when I set a custom folder for the generated steps using integration tests (I'm using the last version 1.3.0):

This is my build.yaml:
`targets:
  $default:
    sources:
      - integration_test/**   # By default, build runner will not generate code in the integration folder
      - test/**               # so we override paths for code generation here
      - lib/**
      - $package$
    builders:
      bdd_widget_test|featureBuilder:
        options:
          include: package:bdd_widget_test/bdd_options.yaml
          stepFolderName: ../../my_steps
          `

And this is the output when I lunch the test:
`org-dartlang-app:/survey_login_test.dart:12:8: Error: Error when reading 'org-dartlang-app:/my_steps/i_see_complex_text.dart': File not found
import './../../my_steps/i_see_complex_text.dart';`

If I remove the stepFolderName the test is working like a charm.

Thanks in advance

**Comment by olexale** [comment]
Hey @jamontes79  👋
What is the folder structure looks like? 
I assume that there is a `survery_login.feature` file somewhere inside the `test` folder, right? Is `../../my_steps/i_see_complex_text.dart` is a correct path for this file?

**Comment by jamontes79** [comment]
Hi @olexale 

Thanks for your quickly answer.

Yes, the folder is under test folder and the path is correct, here is a screenshot from the project
![Screenshot 2022-02-14 at 13 27 09](https://user-images.githubusercontent.com/11333270/153864393-8f820219-f26e-4242-9d45-56fb1b0c3b1f.png)
:

It's seems to be something related with integration tests and relative path, but I'm not sure

**Comment by olexale** [comment]
Unfortunately, I don't see an error on this screenshot. Is it possible for you to prepare a very basic project that illustrates the problem (just remove everything related to your app from this project, and keep only things that are absolutely required for tests to run) and share it with me?

**Comment by jamontes79** [comment]
Sure... I'll try to prepare it during today. 

Thanks a lot! :)

**Comment by jamontes79** [comment]
I've just found the problem.

It seems that integration tests (executing in web) can't find ancestors folders.

So the solution in my case it's to have a main entry point with all generated tests, and now they can find the folders.

Thanks and again, great job with this library.
