### ISSUE TITLE
Code generation 

### ISSUE THREAD

**Issue by vidibu** [olexale/bdd_widget_test#24]
Comments will be included as lines of code in the file generated for running tests if the _.feature_  file starts with those comments.

**Comment by olexale** [comment]
Hey @vidibu, 👋 
I'm not sure understood the issue. Do you have any problem with the feature file header?

**Comment by vidibu** [comment]
Hi @olexale,

Maybe I am mistaken and it is not an issue in case it is prohibited to use comments at the beginning of a feature file.

Let's take for example this [feature file](https://github.com/olexale/bdd_widget_test/blob/master/example/integration_test/sample.feature). We add at the beginning of the file some comments or a documentation string. We get the following:

![Capture](https://user-images.githubusercontent.com/99803259/154280477-7b5f5190-3a57-4ed9-94e9-469b1530cd7c.PNG)
Or
![Capture2](https://user-images.githubusercontent.com/99803259/154280492-8245c317-039f-49d2-9229-23b7b2cb4b2d.PNG)

After running the command to generate the tests (`flutter packages pub run build_runner watch --delete-conflicting-outputs`), the file _[example/integration_test/sample_test.dart](https://github.com/olexale/bdd_widget_test/blob/master/example/integration_test/sample_test.dart)_ becomes as following:


![2](https://user-images.githubusercontent.com/99803259/154281580-4ce6dd3c-e9a6-4753-8b52-837adb2104a8.PNG)
Or
![1](https://user-images.githubusercontent.com/99803259/154281583-10bf72b3-6195-46fd-b48b-fbd8b14c7cf8.PNG)

As you can see, the comments are not being ignored by the builder if they are at the start of the feature file.

**Comment by olexale** [comment]
Ah, I see now. Well, this is "by design". In Gherkin, comments must be placed **after** Feature declaration. So the typical scenario migth be:
```ruby
Feature: My awesome feature
  Here I put the description. By the way, you don't have to use comments here
  You may put Jira task ID, or any other stuff.

  Scenario: And that is the scenario.
```

Everything that is before Feature is reserved for good old copy-paste, it's a technical zone, which btw I'd recommend to use carefully.

**Comment by vidibu** [comment]
Thanks a lot for your clear answer !
