### ISSUE TITLE
Mapping of the step in the .feature file to its step definition 

### ISSUE THREAD

**Issue by IliyanBogdanov** [olexale/bdd_widget_test#27]
https://github.com/olexale/bdd_widget_test/blob/02cb81fce2f265e5e8fb7d19ce808c624e92a66e/example/integration_test/sample.feature#L4

Hi Olex,

Thanks a lot for this very useful package. We are currently applying it in our flutter project for e2e testing solution(automation of the regression test suite) and we find it very useful and without an alternative. The only thing that we miss for now is the mapping of the step in the .feature file to its step definition (command+click on the step in the .feature file opens the step definition). It brings readability, maintainability and is more useful in the reports. Our question is - is it doable in a fork, in your opinion?

Thanks a lot in advance,
All the best,
Iliyan

**Comment by olexale** [comment]
Hi Iliyan,

Thank you!

This does not sound like a feature of the package, but rather a plugin for your IDE. For example, [here](https://marketplace.visualstudio.com/items?itemName=cucumber-mapper-ruby.cucumber-mapper-ruby) is a similar plugin for ruby and cucumber.

Kind regards,
Oleksandr

**Comment by olexale** [comment]
Hey Iliyan,

I'm closing the ticket but feel free to reopen it if you think that we may proceed with this issue somehow or if you have other questions on this topic.

Thanks!

**Comment by olexale** [comment]
Hey Iliyan,

I'm closing the ticket but feel free to reopen it if you think that we may proceed with this issue somehow or if you have other questions on this topic.

Thanks!
