### ISSUE TITLE
It can implement with golden_test?

### ISSUE THREAD

**Issue by tot14883** [olexale/bdd_widget_test#35]
I'm wondering this package support golden_test, or not? https://pub.dev/packages/golden_toolkit

**Comment by olexale** [comment]
Yes, that's described in the [README](https://pub.dev/packages/bdd_widget_test) file. There is even a [video tutorial](https://www.youtube.com/playlist?list=PLjaSBcAZ8TqFx51f30aRi_A2szelttOpq) on that.
