### ISSUE TITLE
Is it possible add multiples include imports on build.yaml?

### ISSUE THREAD

**Issue by juanagu** [olexale/bdd_widget_test#36]
Hello, we want to import from our main app steps from different packages. Is it possible to do something like this:
```
includes:
 - package:feature_a/bdd_options.yaml
 - package:feature_b/bdd_options.yaml
```

**Comment by olexale** [comment]
Hey 👋 Not yet, currently only single options file is supported. I see why this might be useful, hence I believe it can be a nice improvement.
Let's keep it as a feature request.

**Comment by olexale** [comment]
@juanagu, this should work in `1.4.3`. the syntax is the same as with steps:
```yaml
include:
  - package:package_one/bdd_options.yaml
  - package:package_two/bdd_options.yaml
```

Would you please test?

**Comment by olexale** [comment]
I assume that it works, so I’m closing this ticket.
