### ISSUE TITLE
runAsync option?

### ISSUE THREAD

**Issue by psovit** [olexale/bdd_widget_test#37]
Is there a way to use `tester.runAsync(() async { .... });` option with this package using code-generation?

**Comment by olexale** [comment]
You may write something like this in a step implementation:
```dart
await tester.runAsync<void>(() => Future.delayed(Duration(seconds: 5)));
```
Is it something you want to achieve with `tester.runAsync`?

**Comment by psovit** [comment]
Actually I wanted to see if the whole scenario can be wrapped around `tester.runAsync` and not just an individual step.

**Comment by olexale** [comment]
You can not wrap the whole scenario, but most probably, that's not what you need. You can use `tester.runAsync` in steps, and that should do. Do you have an example where it will not work?

**Comment by psovit** [comment]
Yeah, I managed to organize my code/test to avoid having to use `tester.runAsync` in scenario. Thanks :)
