### ISSUE TITLE
Add a "Background" step for all generated tests

### ISSUE THREAD

**Issue by ynlvko** [olexale/bdd_widget_test#41]
All my tests begin with a "Given prelude" step, setting up GetIt, HttpMockAdapter, default values for Mocks, SharedPrefs, etc. So all my Features or each Scenario have to start with "Background: Given prelude". Is there a way to predefine steps for all generated tests?

**Comment by olexale** [comment]
According to the Gherkin [specification](https://cucumber.io/docs/gherkin/reference/#background), the Background step is defined on a Feature level.

But not all is lost. You may create your own test runner function (like [testGoldens](https://github.com/eBay/flutter_glove_box/blob/5af8ed5285d9fa261e5db054cbeab22814a93e32/packages/golden_toolkit/lib/src/testing_tools.dart#L150) from golden_toolkit or `testWidgets` itself, which is just a wrapper for `test`) and then override the runner function for the whole project as described [here](https://github.com/olexale/bdd_widget_test#how-to-test-the-ui-golden-tests).

**Comment by olexale** [comment]
@ynlvko, do you think we may close this issue?
