### ISSUE TITLE
Change void main to Future<void>

### ISSUE THREAD

**Issue by jaumard** [olexale/bdd_widget_test#49]
I don't want to run each test file one at the time cause it take forever and rebuild everything each time. 

So what I'm used to do is to load each main into a master main and launch them sequentially like:

```dart

void main() {
  await main1();
  await main2();
  ....
}
```

Currently that's not doable here. Is this something you could add? Or is there another way to do it ?

**Comment by olexale** [comment]
Not sure how this is related to the package, but you can achieve this by either manually creating the `main` function from which you call other main functions, like described [here](https://betterprogramming.pub/how-i-reduced-flutter-integration-suite-result-time-by-approx-50-adddffb12cbf), or use a custom test runner, that will do this for you, like [this one](https://cli.vgv.dev/docs/commands/test).
