### ISSUE TITLE
Use patrol and golden_toolkit in the same feature

### ISSUE THREAD

**Issue by gcostaapps** [olexale/bdd_widget_test#57]
Hi, first I want to thank you for this awesome package, it's really great and well documented!

Is there any workaround to use both patrol and golden_toolkit in the same scenario?

I've tried different ways but couldn't find a way to work it. I saw the #44 and I'm playing around the testMethods/testName/testerType to create a new type that have the PatrolTester and WidgetTester and wrap the goldenTests/patrol testers with my own method that pass the correct variable accordingly to what's need and use this type in the steps.

I would like to know if you came with this problem and maybe solved it or if you find a useful way to do it.

___ 
Edit

After playing a bit I found a useful way to do it. Will put here if someone needs to do the same:

Added this option to buid.yaml

```
testMethodName: testGoldensWithPatrol
testerName: tester
testerType: CustomTester
```

Create a file with this new types

```
import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:golden_toolkit/golden_toolkit.dart';
import 'package:patrol_finders/patrol_finders.dart';
import 'package:meta/meta.dart';

typedef WidgetTesterWithPatrolCallback = Future<void> Function(CustomTester);

typedef CustomTester = ({PatrolTester $, WidgetTester tester});


@isTest
Future<void> testGoldensWithPatrol(
    String description, WidgetTesterWithPatrolCallback callback) async {
  return testGoldens(description, (widgetTester) async {
    const config = PatrolTesterConfig();

    final patrolTester = PatrolTester(
      tester: widgetTester,
      config: config,
    );

    await callback(($: patrolTester, tester: widgetTester));
  });
}
```

Then I added the import this file on my .feature files and in the steps I use the CustomTester, generally using patrol but using the widgetTester as need to compare the goldens.

**Comment by olexale** [comment]
Hey @gcostaapps,
Yeap, that's the way. 👍 Do you think we may close this ticket?

**Comment by gcostaapps** [comment]
@olexale sure! Closing it, thanks!
