### ISSUE TITLE
Add support for data tables in background and after

### ISSUE THREAD

**Issue by daniel-deboeverie-lemon** [olexale/bdd_widget_test#61]
Maybe a bit backwards to make the pr before the issue, but I am in need to be able to use data tables in the background.

  Background:
    Given I have an account with
      | "login" | "test@lemon.be" |
      | "pin"   | "12345"           |
    And the app is running
    And I am on the {'/login'} screen

This is an example of how I wish to use it.

**Comment by olexale** [comment]
Hey Daniel 👋
Thanks for the PR, I already had a look and so far it looks great. I'll secure a bit of time for tomorrow to review it properly and publish a new version if all is good.

**Comment by olexale** [comment]
Fixed under #60. I'll publish a new version once I review/merge other opened PRs.
