### ISSUE TITLE
Can we have separate folder for feature and test files?

### ISSUE THREAD

**Issue by hungcaovn** [olexale/bdd_widget_test#79]
Currently the test files are created in the same folder with feature files. Any ideas if we could put the feature files in a folder (aka features) and test files in another one?

**Comment by olexale** [comment]
From my knowledge, that's not possible with this package. Is there any particular reason you want to have them separated?

**Comment by hungcaovn** [comment]
@olexale : No actually I just want to make it is organized better. Thank you for an awesome package!

**Comment by olexale** [comment]
in that case, I'd recommend you configure file nesting in your IDE.

### VSCode
here is my VSC configuration:
<img width="874" alt="Знімок екрана 2024-06-13 о 19 31 37" src="https://github.com/olexale/bdd_widget_test/assets/4376913/2ae9817c-5571-4c78-a0c8-9f7c3d91eb12">

and what's what it looks like in the explorer:
<img width="295" alt="Знімок екрана 2024-06-13 о 19 28 59" src="https://github.com/olexale/bdd_widget_test/assets/4376913/03ab0246-f5cb-4f40-be43-70958902d9eb">

### Android Studio
for Android Studio it is similar:
<img width="595" alt="Знімок екрана 2024-06-13 о 19 36 08" src="https://github.com/olexale/bdd_widget_test/assets/4376913/d8205f2d-8ee4-4d67-bce5-ae715129e936">

I hope that helps. do you think we may close the ticket?

**Comment by hungcaovn** [comment]
@olexale : Thank you for your suggestion. I will close this ticket
