### ISSUE TITLE
Is it possible to use your solution with golden_toolkit ?

### ISSUE THREAD

**Issue by BondarenkoArtur** [olexale/bdd_widget_test#8]
Your widget testing library is really cool one and I'm thinking about using it for comparing with screenshots.

I'm curious is it possible to use it for cases when [golden_toolkit](https://pub.dev/packages/golden_toolkit) is installed and when instead of `testWidgets`, `testGoldens` should be used?

**Comment by olexale** [comment]
Currently, `testWidgets` string is hardcoded in the plugin, but I think it makes sense to add a parameter that will tell the plugin whether it needs to generate a widget test, a flutter driver test, or a golden test.

**Comment by olexale** [comment]
quick update: this should be possible with version 0.7.1, but I didn't have time to write documentation yet. I plan to finish this next week.

**Comment by olexale** [comment]
I've updated the [README file](https://github.com/olexale/bdd_widget_test#how-to-test-the-ui-golden-tests) with some guidelines and published a [video](https://youtu.be/FBLXvqldUGI) with some live demo. I think we may close this issue now 🙂
